name: PyTest and Publish

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  test1:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - run: |
          sudo apt-get update -q -q
          sudo apt-get install --yes ffmpeg

      - name: Install uv
        uses: astral-sh/setup-uv@v10.3.0

      - name: Install dependencies
        run: uv sync --locked --no-editable --extra test

      - name: Run missing modules test
        run: uv run --locked --extra test pytest tests/test_modules.py  # should run before deluxe deps installed

      - name: Run deluxe pytest
        run: |
          uv sync --locked --no-editable --extra test --extra deluxe
          uv run --locked --extra test --extra deluxe pytest

  test2:
    needs: test1
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        nv: [ {os: windows-latest, py: "3.14"}, {os: macos-latest, py: "3.13"} ]

    runs-on: ${{ matrix.nv.os }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v10.3.0

      - name: Set up Python ${{ matrix.nv.py }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.nv.py }}

      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q -q
          sudo apt-get install --yes ffmpeg
      - if: runner.os == 'macOS'
        run: |
          brew uninstall bicep || true
          brew untap aws/tap azure/bicep || true
          brew install ffmpeg
      - if: runner.os == 'Windows'
        run: choco install ffmpeg

      - name: Install Dependencies
        run: uv sync --locked --no-editable --extra test

      - name: Run deluxe pytest
        run: |
          uv sync --locked --no-editable --extra test --extra deluxe
          uv run --locked --extra test --extra deluxe pytest

  publish:
    needs: [test1, test2]
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v10.3.0

      - run: uv build --no-sources --clear
      - run: uv publish

  release:
    needs: publish
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - run: gh release create ${{ github.ref_name }} --repo ${{ github.repository }} --title "Release ${{ github.ref_name }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
