name: Tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
