name: PyTest

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        environment: ["py36", "py37", "py38", "py39", "flake8"]

        include:
          - environment: "py36"
            python: "3.6"
          - environment: "py37"
            python: "3.7"
          - environment: "py38"
            python: "3.8"
          - environment: "py39"
            python: "3.9"
          - environment: "flake8"
            python: "3.7"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry pytest
          apt update
          apt install -y ffmpeg mpv

      - run: poetry install
      - run: poetry build
      - run: pytest
