name: PyTest

on:
  push:
    branches:
      - main
    tags-ignore:
      - "v*"

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python: ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry pytest
          poetry config virtualenvs.create false

      - run: poetry install
      - run: poetry build
      - run: pytest
